"""Curated graha-in-bhava text for the eight grahas the teacher has not yet covered (Moon … Ketu).

Each point blends fields the page already holds — the graha's PLANET_PROFILE / KARAKATWAS entry and the
bhava's BHAVA_INFO entry (signification, body, relatives) — in the register of the Sun slides: what the
placement can give and what to watch.  Nothing here is slide text; every row is tagged `curated` and the
teacher's own wording replaces it once she teaches the graha (edit Session23_Rules.xlsx, GrahaInBhava).
"""

PROFILE_FIELDS = {
    "Moon": "Relationships, Personality Traits, Profession / Status, Body Parts Ruled, General Health Indicator",
    "Mars": "Relationships, Personality Traits, Profession / Status, Body Parts Ruled, General Health Indicator",
    "Mercury": "Relationships, Personality Traits, Profession / Status, Body Parts Ruled, General Health Indicator",
    "Jupiter": "Relationships, Personality Traits, Profession / Status, Body Parts Ruled, General Health Indicator",
    "Venus": "Relationships, Personality Traits, Profession / Status, Body Parts Ruled, General Health Indicator",
    "Saturn": "Relationships, Personality Traits, Profession / Status, Body Parts Ruled, General Health Indicator",
}
HOUSE_FIELDS = "sig, body, rel"

DATA = {}

DATA["Moon"] = {
    1: ["With the Moon in the 1st, the self is gentle, caring and sensitive; the personality is imaginative and the mood can change as quickly as emotions do.",
        "The 1st house is the body and appearance, so the Moon's soft, feminine, water-element nature is often seen in a rounded, pleasant look and in popularity with the public.",
        "A strong, waxing Moon gives an easy rapport with people; a weak or waning Moon can bring restlessness, mental strain and a tendency towards cold, phlegm and low immunity.",
        "The mother and the Moon's emotional memory shape the life path; peace of mind is the lesson."],
    2: ["The Moon in the 2nd softens speech: words are gentle, caring and emotional, and the person is deeply attached to family and lineage.",
        "Wealth and savings rise and fall like the Moon; income can come through milk, food, hotel, grocery or other public-facing trades, and money often follows the mood.",
        "Food habits matter here: a liking for milk-based and comfort food; the face and eyes (the Moon rules the left eye) deserve care.",
        "This is also a Maraka house, so emotional stress over family and money can disturb the mind during the Moon's period."],
    3: ["The Moon in the 3rd gives a sensitive, imaginative way of communicating; writing, media and the arts of expression come naturally.",
        "There is a close emotional bond with younger siblings and neighbours, and frequent short journeys; courage is real but fluctuates with the mood.",
        "Self-effort asks for steady routine, as the Moon's changeability can interrupt hobbies and business drives.",
        "Neck, shoulders and ears may carry the tension of an overworked mind."],
    4: ["The Moon is a natural karaka of the 4th: attachment to the mother, home and motherland is deep, and peace of mind depends on the domestic atmosphere.",
        "Ancestral or landed property, vehicles and a comfortable home are often part of the story; schooling up to graduation goes smoothly when the mind is settled.",
        "A strong Moon here gives contentment; a weak or waning Moon can bring restlessness at home, changes of residence and chest or lung sensitivity.",
        "Emotions are the key lesson: nurture others without being swallowed by moods."],
    5: ["The Moon in the 5th gives an imaginative, creative mind with a flair for music, drama, poetry and entertainment.",
        "Love and romance are emotional and sincere; the bond with children is nurturing and protective.",
        "Studies and mantra upasana flourish when the mind is calm; speculation (stock market, lottery) follows mood, so caution is wise.",
        "Digestion and the stomach are sensitive to worry; past-life merit shows as intuition."],
    6: ["The Moon in the 6th makes the mind vulnerable to worry over enemies, debts and daily routine; stress tends to show as digestive or fluid disorders.",
        "Service in caring fields — nursing, hospitality, healing — can use the Moon's sensitivity well, and the 6th improves with time.",
        "Cold, cough, phlegm and low immunity are the usual health signals; disputes with colleagues are softened by a gentle approach.",
        "The mother or maternal relatives may need care; emotional eating or habits are worth watching."],
    7: ["The Moon in the 7th points to a caring, emotionally attached spouse and a marriage that is shaped by feelings and mutual care.",
        "Dealings with the public and the market are a strength: hotel, dairy, travel and other mass-facing businesses suit this placement.",
        "Moods in partnerships can swing; clear communication helps. This is a Maraka house, so mental strain in close partnerships deserves attention.",
        "Kidneys and the urinary bladder are the body parts to look after."],
    8: ["The Moon in the 8th brings depth of feeling, intuition and an interest in the occult, research and hidden matters.",
        "The mind can go through anxiety and sudden emotional turns; sudden events or unexpected changes tend to be felt on the inside first.",
        "Inheritance or support may come through the mother or women; chronic fluid, bladder or mental-health issues call for regular care.",
        "Transformation is the lesson: emotional anchoring and a spiritual routine give stability."],
    9: ["The Moon in the 9th gives a devotional, nurturing view of dharma; fortune tends to come through the public, travel and the blessings of the mother.",
        "There is emotional respect for gurus, teachers and the father's line; higher studies and pilgrimage appeal.",
        "Beliefs may shift with moods; steady practice keeps faith grounded.",
        "Long journeys, especially by or near water, can be rewarding."],
    10: ["The Moon in the 10th gives public-facing careers — hotel industry, nursing, travel, dairy, agriculture, caring professions — and fame through popularity with the public.",
         "Reputation follows emotions: it can rise and fall, and career changes are common.",
         "The mother may influence the choice of work; authority is exercised with care rather than force.",
         "Knees and the mind are the body areas to protect from overwork."],
    11: ["The Moon in the 11th favours gains through the public, friends and women; the network is wide and emotionally warm.",
         "Income comes in waves rather than in a straight line; desires are fulfilled through steady, regular effort.",
         "Elder siblings and friends are caring, though moods in friendships need patience.",
         "Large organisations and public-oriented ventures suit this placement."],
    12: ["The Moon in the 12th gives a vivid dream life, deep sleep needs and a taste for bed comforts, solitude and retreat.",
         "Expenses tend towards comfort, family and charity; residence abroad or in secluded places is possible.",
         "The mind can over-think; the left eye (ruled by both the Moon and the 12th) and sleep need care.",
         "Spiritual practice, hospitals, ashrams and quiet service suit this placement and bring peace of mind."],
}

DATA["Mars"] = {
    1: ["Mars in the 1st makes the person courageous, energetic and action-oriented; the personality is assertive, hasty and competitive.",
        "The body is athletic and the head and face may carry scars, cuts or marks; the 1st is the head, so headaches and blood-pressure swings are worth watching.",
        "Temper and impulsiveness are the lesson: leadership works best when anger is channelled into action.",
        "Marriage is traditionally checked for Kuja (Mangal) dosha with this placement."],
    2: ["Mars in the 2nd gives sharp, blunt speech; family discussions can turn into arguments if anger is not controlled.",
        "Wealth comes through effort, property, engineering or energetic professions; impulsive spending can drain savings.",
        "Teeth, mouth and face are the body areas to protect; spicy and hot food is favoured.",
        "Kuja dosha is checked here for marriage; this is also a Maraka house, so heated disputes at home are best avoided."],
    3: ["Mars is the natural karaka of the 3rd: courage, stamina and will-power are strong, and self-effort pays off over time.",
        "The bond with younger siblings can be protective or competitive; sports, defence, mechanical work and bold writing or media suit the person.",
        "Short journeys are frequent; the drive to do business is high, though haste can cause mistakes.",
        "Arms, shoulders and the neck need care from strain or injury."],
    4: ["Mars is the Bhoomi karaka, so in the 4th the interest in land, property, construction and vehicles is strong.",
        "Peace of mind and domestic harmony can be disturbed by anger or restlessness; the mother's health or temperament deserves attention.",
        "The chest, heart and blood pressure need monitoring.",
        "Kuja dosha is checked here for marriage; patience at home turns the energy into security."],
    5: ["Mars in the 5th gives a sharp, competitive intellect with a flair for sports, strategy, engineering and quick decisions.",
        "Romance is impulsive and passionate; children are energetic and strong-willed and may need guidance.",
        "Speculation is risky; mantra upasana of a fiery deity channels the energy well.",
        "Acidity and heat in the stomach and liver call for a cooling diet."],
    6: ["Mars is strong in the 6th: it helps win over enemies, competitors and debts, and the spirit of competition is high.",
        "Police, army, security, surgery, medicine and other healing or service fields suit this placement.",
        "Cuts, inflammations, accidents and infections of the small intestine are the cautionary side; litigation is won with vigour but not with haste.",
        "The 6th improves with time, so results strengthen steadily."],
    7: ["Mars in the 7th brings passion and force into partnerships; the spouse is energetic and strong-willed, and ego clashes are the main risk.",
        "Business partnerships need clear boundaries and shared decisions; dealings with the public are bold.",
        "Kuja dosha is traditionally checked for marriage; this is also a Maraka house, so heated disputes and health strain in close ties are worth avoiding.",
        "Kidneys, bladder and the urinary system need care."],
    8: ["Mars in the 8th brings courage in crises and an interest in research, surgery, investigation and the occult.",
        "Sudden events, accidents, injuries, bleeding and surgeries are the cautionary side; care with speed, fire and sharp tools is wise.",
        "Inheritance or insurance may come through struggle; stamina for long-lasting problems is good.",
        "Kuja dosha is checked here for marriage; the spouse's family is an influence."],
    9: ["Mars in the 9th gives a crusading, action-oriented approach to dharma; fortune comes through effort rather than luck.",
        "Friction with the father, gurus or teachers is possible, though respect grows with maturity.",
        "Moral standards are strongly defended; long-distance travel and pilgrimages are adventurous.",
        "The thighs and hips are the body areas to protect from injury."],
    10: ["Mars in the 10th gives drive, authority and a talent for leading: engineering, police, army, surgery, sports and supervisory roles suit this placement.",
         "Recognition comes through valour and achievement, and property or land may be part of the profession.",
         "Clashes with superiors or rivals are the cautionary side; steady, patient effort turns the energy into lasting status.",
         "The knees need care from heavy physical work."],
    11: ["Mars in the 11th gives gains through energy, property, machinery and competitive effort; ambitions are fulfilled by steady action.",
         "The network is energetic and competitive; elder siblings and friends can be supportive, though quarrels in the group need watching.",
         "Income grows with time; success comes in large undertakings.",
         "Legs and left ear are the body areas to protect from strain."],
    12: ["Mars in the 12th directs energy outwards into expenses, travel abroad, hospitals or hidden battles; anger is best released through discipline and exercise.",
         "Secret enemies, losses through disputes or confiscations are the cautionary side.",
         "Sleep and bed comforts can be disturbed; the feet and left eye need care.",
         "Kuja dosha is checked here for marriage; seclusion, retreat or service abroad can use the energy well."],
}

DATA["Mercury"] = {
    1: ["Mercury in the 1st gives a bright, youthful, communicative personality: intelligent, adaptable, friendly and quick to learn.",
        "Speech and wit shape first impressions; the person can be diplomatic, but also calculating or restless when under stress.",
        "Mercury takes the colour of the planets it joins, so its results here depend on its company and strength.",
        "Skin, nerves and the nervous system are the health areas to look after; anxiety shows up in the body."],
    2: ["Mercury in the 2nd gives pleasant, intelligent speech and a talent for persuasion, teaching, writing and business.",
        "Wealth comes through knowledge, trade, accounts or communication; the family is learned and values education.",
        "Early schooling goes well; the tongue, throat and teeth need care, and speech can turn cunning if the company is poor.",
        "This is also a Maraka house, so nervous stress over money and family is the point to watch."],
    3: ["Mercury in the 3rd suits writing, publishing, media, marketing, short journeys and all forms of communication.",
        "The drive to do business is strong and the person is skilful with hands and gadgets; courage is mental rather than physical.",
        "Younger siblings and neighbours are friendly and talkative; hobbies and learning continue throughout life.",
        "Overwork can strain the hands, shoulders and nerves."],
    4: ["Mercury in the 4th favours schooling, education up to graduation and a home filled with books, conversation and learning.",
        "Peace of mind comes through study and routine; the mother, or home life, may be intellectual and talkative.",
        "Property or vehicles may come through dealings, trade or brokerage; restlessness can bring frequent changes at home.",
        "Anxiety can settle in the chest and lungs."],
    5: ["Mercury in the 5th gives intelligence, wit and talent for higher studies, teaching, writing, mathematics and strategy.",
        "Romance is playful and friendly; children are bright and talkative, and the person enjoys guiding them.",
        "Speculation is attractive but calculated risks beat impulsive ones; mantra and upasana grow through study.",
        "Digestion and the stomach are sensitive to nervous tension."],
    6: ["Mercury in the 6th gives skill at analysing problems, debts and disputes; it favours accounting, medicine, law and daily service work.",
        "Enemies are handled through diplomacy; the competitive spirit is intellectual.",
        "Skin, nerves, intestinal and sore-throat troubles are the cautionary side; worry and over-analysis can wear the person down.",
        "The 6th improves with time, so skill grows steadily with experience."],
    7: ["Mercury in the 7th brings a youthful, intelligent, communicative spouse, and a marriage built on conversation and friendship.",
        "Business partnerships, trading and brokerage are favoured; dealings with the public and market are smooth.",
        "A critical or calculating attitude can strain relationships; honest talk keeps partnerships healthy. This is also a Maraka house.",
        "Foreign travel and trade can bring benefits."],
    8: ["Mercury in the 8th gives a probing mind with interest in research, investigation, astrology, the occult and hidden knowledge.",
        "Money may come through inheritance, insurance or the spouse's family; speech can be secretive or sharp.",
        "Nervous strain, skin or throat problems and sudden anxieties deserve care; chronic issues are best handled with regular routines.",
        "Studies in depth-oriented subjects are rewarding."],
    9: ["Mercury in the 9th gives a curious, philosophical mind: higher studies, teaching, writing on dharma and learning from gurus are favoured.",
        "Fortune comes through knowledge, publishing, travel and communication; relations with the father's line are intellectual.",
        "Pilgrimage and long-distance travel broaden the mind; belief may be questioned before it is accepted.",
        "Thighs and nerves need care when the mind is overactive."],
    10: ["Mercury in the 10th gives careers in teaching, writing, publishing, accounting, trading, brokerage, journalism or public speaking.",
         "Status comes through intelligence, communication and adaptability; the reputation is that of a smart, versatile professional.",
         "Changing jobs or running more than one line of work is common; diplomacy helps with authority.",
         "Knees and nerves may suffer when work stress builds."],
    11: ["Mercury in the 11th favours profits through business, trade, communication and networks; friends are intelligent and helpful.",
         "Income is regular and often comes from several sources; large organisations and online or media networks suit the person.",
         "Desires are fulfilled through learning and clever dealings; elder siblings and well-wishers are supportive.",
         "Too many commitments can scatter the energy."],
    12: ["Mercury in the 12th gives a thoughtful, imaginative mind that works best in solitude: writing, research, foreign work or study abroad.",
         "Expenses go towards education, communication and travel; sleep can be light because the mind stays active.",
         "Hospitals, ashrams and seclusion suit the mind; secret anxieties and nervous exhaustion are the cautionary side.",
         "Feet and the left eye need care."],
}

DATA["Jupiter"] = {
    1: ["Jupiter in the 1st gives a wise, benevolent, optimistic personality with a dignified presence and natural respect from others.",
        "The body tends to grow broad with age; health is protected, though liver, fat and digestion call for moderation.",
        "The life path is guided by values, teachers and good counsel; generosity and spiritual interest are marked.",
        "Excess and over-confidence are the cautionary side."],
    2: ["Jupiter is the natural karaka of the 2nd: wealth, family and speech are blessed, and savings accumulate steadily.",
        "Speech is wise, kind and respected; the family is cultured and values education and dharma.",
        "Banking, finance, teaching and counselling are natural income sources; food habits favour sweets and rich food.",
        "This is also a Maraka house; moderation protects health and finances."],
    3: ["Jupiter in the 3rd gives a wise, optimistic style of communication and a talent for teaching, writing and counselling.",
        "Courage is of the moral kind rather than the physical; siblings are well-wishing and the bond with younger siblings is good.",
        "Efforts are rewarded steadily, but laziness or over-confidence can reduce the drive.",
        "Short journeys and hobbies are enriching."],
    4: ["Jupiter in the 4th brings contentment at home, a respected mother and a good education; domestic happiness is a strength.",
        "Landed and ancestral property, vehicles and a comfortable home are indicated; the heart and peace of mind are protected.",
        "A teacher or guru can be a part of the home life.",
        "Complacency and weight gain are the cautionary side."],
    5: ["Jupiter is the natural karaka of the 5th: children, creativity, intelligence, higher education and mantra upasana are blessed.",
        "The person is respected as an adviser; love and romance are sincere and generous.",
        "Speculation and entertainment bring gains in moderation; past-life merit supports wisdom and good fortune.",
        "Liver, gall bladder and stomach need care in excess."],
    6: ["Jupiter in the 6th protects against enemies and obstacles, though it can weaken the 'fighting' spirit that the 6th usually asks for.",
        "Service in medicine, law, counselling or finance suits the placement; debts are managed with wise advice.",
        "Liver, pancreas, diabetes and weight issues are the cautionary side; litigation is best settled by counsel.",
        "The 6th improves with time, so the results ripen steadily."],
    7: ["Jupiter in the 7th gives a wise, generous, respected spouse and a marriage built on shared values.",
        "Business partnerships, clients and dealings with the public are favourable; advice and counselling bring success.",
        "Over-expectation in partnerships is the lesson; moderation protects the relationship. This is also a Maraka house.",
        "Foreign travel and trade can bring good opportunities."],
    8: ["Jupiter in the 8th protects longevity and supports study of the occult, philosophy, astrology and hidden wisdom.",
        "Inheritance, insurance or the spouse's family may bring support; sudden events are cushioned by good counsel.",
        "Chronic liver, digestive or weight issues deserve regular care; transformation is gentle rather than abrupt.",
        "Research and depth-oriented teaching are rewarding."],
    9: ["Jupiter is the natural karaka of the 9th: fortune, dharma, gurus, the father and pilgrimage are blessed.",
        "Higher studies and teaching come easily; the person is generous, ethical and respected as an adviser.",
        "Long-distance travel and temples bring growth; belief and grace work together.",
        "Dogmatism and complacency are the cautionary side."],
    10: ["Jupiter in the 10th gives status through wisdom: judge, adviser, banker, minister, priest, teacher or counsellor roles suit the person.",
         "Reputation is that of an honest, benevolent authority; recognition grows steadily.",
         "Ethics shape career decisions; ambition is balanced by principle.",
         "Knees (ruled by the 10th) and weight gain from a sedentary, desk-bound career need care."],
    11: ["Jupiter in the 11th gives abundant gains, supportive friends and fulfilment of desires; the network is wide, wise and generous.",
         "Income often comes from teaching, finance, advisory or large organisations.",
         "Elder siblings and well-wishers support success; savings grow into lasting wealth.",
         "Over-optimism in speculation is the cautionary side."],
    12: ["Jupiter in the 12th favours spirituality, charity, meditation, retreats and moksha; expenses go to good causes.",
         "Foreign residence, hospitals, ashrams and teaching abroad suit the placement.",
         "Sleep and bed comforts are good; indulgence and over-spending are the cautionary side.",
         "The feet and the left eye need care."],
}

DATA["Venus"] = {
    1: ["Venus in the 1st gives a pleasant, charming, refined personality with an artistic eye and a love of beauty and comfort.",
        "The appearance is attractive and well groomed; relationships and social life come easily.",
        "Luxury-loving habits can turn into indulgence; kidneys, hormones and sugar balance deserve moderation.",
        "The person is romantic and values harmony."],
    2: ["Venus in the 2nd gives a sweet, melodious voice, a love of good food and a family that values art, culture and comfort.",
        "Wealth comes through beauty, art, jewellery, silk, hospitality or luxury goods; savings grow when spending on pleasure is balanced.",
        "The face, cheeks and eyes are attractive; sweet foods may affect sugar levels.",
        "This is also a Maraka house; strain in family or money matters can affect the kidneys."],
    3: ["Venus in the 3rd gives artistic communication — music, writing, design, media — and a charming way with neighbours and siblings.",
        "Courage is gentle and diplomatic; the drive in business shows through creative ventures.",
        "Short journeys for pleasure are favoured; the bond with younger siblings is warm.",
        "Comfort-seeking can reduce self-effort if not balanced."],
    4: ["Venus is a natural karaka of the 4th: a comfortable, beautiful home, good vehicles and domestic happiness are indicated.",
        "The mother is refined and loving; education includes arts and culture; property and fixed assets are favoured.",
        "Contentment at home gives peace of mind; the chest and heart respond to emotional health.",
        "Over-attachment to comfort is the cautionary side."],
    5: ["Venus in the 5th gives romance, creativity, and talent in music, dance, cinema, drama and the arts; love is sincere and expressive.",
        "Children are charming and artistic; the intellect is refined and appreciates beauty.",
        "Speculation and entertainment can bring gains; excess pleasure-seeking is the cautionary side.",
        "Mantra and upasana of a gentle deity bring peace."],
    6: ["Venus in the 6th can weaken comfort and relationships through disputes, debts and domination; the spouse may be demanding.",
        "Service in beauty, hospitality, healing or arts suits the placement, and enemies are won over by charm.",
        "Kidney, urinary, hormonal, sugar and venereal issues are the cautionary side; avoid excess in pleasures.",
        "The 6th improves with time, so the results ripen gradually."],
    7: ["Venus is the karaka of the 7th: a charming, affectionate, artistic spouse and a harmonious marriage are indicated.",
        "Business partnerships, clients, hospitality and dealings with the public flourish; foreign travel and trade are favoured.",
        "Over-indulgence or too many attachments are the cautionary side. This is also a Maraka house, so kidneys and the reproductive system need care.",
        "Social interactions, dealings with the masses and a pleasant public manner bring success in partnership-based work."],
    8: ["Venus in the 8th can give hidden wealth, inheritance or support from the spouse's family; there is a deep, intense approach to relationships.",
        "Interest in occult, research and the secret side of art is common; sudden changes in love life are possible.",
        "Reproductive, urinary and hormonal issues require regular care; moderation protects longevity.",
        "Transformation of values is the lesson."],
    9: ["Venus in the 9th gives a refined sense of dharma, devotion through music and art, and fortune that comes through grace and relationships.",
        "Pilgrimages, long-distance travel and higher studies in arts or culture are favoured.",
        "Respect for gurus is warm; the father's line may be artistic.",
        "Comfort-seeking while travelling is the cautionary side."],
    10: ["Venus in the 10th gives careers in beauty, fashion, arts, music, jewellery, hospitality and event management.",
         "Status comes through charm, creativity and the ability to bring people together; the public image is attractive.",
         "Work in luxury or entertainment suits the placement; relationships may mix with career.",
         "Knees (ruled by the 10th) and the kidneys need care when work becomes stressful."],
    11: ["Venus in the 11th gives profits through art, beauty, luxury and relationships; friends are charming and the social circle is wide.",
         "Desires for comfort and pleasure are fulfilled, often through women or partnerships.",
         "Elder siblings and well-wishers support success; income is comfortable.",
         "Overspending on luxury is the cautionary side."],
    12: ["Venus in the 12th gives pleasure in bed comforts, travel, foreign places and spending on luxury and art.",
         "Sleep is good; romance may be private or secret; residence abroad is possible.",
         "Hospitals, retreats and charitable work can be soothing; losses through indulgence are the cautionary side.",
         "Feet, the left eye and kidneys need care."],
}

DATA["Saturn"] = {
    1: ["Saturn in the 1st gives a serious, disciplined, patient personality; a strong Saturn brings maturity and perseverance, a weak one lethargy and an inferiority complex.",
        "The body is lean and the look serious; the self matures slowly and gains confidence with age.",
        "Chronic ailments, joint stiffness and low vitality are the health signals; regular routine protects the body.",
        "Hard work is the life lesson."],
    2: ["Saturn in the 2nd gives careful, measured speech and a cautious attitude to money; wealth builds slowly through discipline.",
        "Family responsibilities are heavy and the family may be conservative or elderly; food habits are simple.",
        "Teeth, face and throat need care; delays in savings are the cautionary side.",
        "This is also a Maraka house, so stress over family and money is best handled with patience."],
    3: ["Saturn in the 3rd gives persistent effort and steady courage; success comes through hard work, not haste.",
        "The bond with younger siblings can be distant or burdened with responsibility; communication is careful and slow.",
        "Writing, technical work and service-oriented ventures suit the placement.",
        "Shoulders, arms and ears need care."],
    4: ["Saturn in the 4th can give a distant home life, an elderly or burdened mother and delayed peace of mind.",
        "Property, vehicles and fixed assets come late in life through effort; education is slow but thorough.",
        "Emotional coldness at home or early separation from the mother is the cautionary side.",
        "Chest and lungs need regular care."],
    5: ["Saturn in the 5th can delay or limit children, though it brings seriousness, depth and discipline to intellect and study.",
        "Romance is slow and cautious; speculation is not favoured and creativity grows through discipline.",
        "Mantra upasana through steady routine brings results; stomach and digestion are sensitive.",
        "Patience with children and teachers is the lesson."],
    6: ["Saturn in the 6th is a strong placement: it helps overcome enemies, debts and obstacles through discipline and patient work.",
        "Service, labour, healing and daily routine suit the person; colleagues and employees are well managed.",
        "Chronic ailments, digestion and joint issues are the cautionary side; the results improve with time.",
        "Disputes and litigation are settled gradually, usually in favour of the patient party."],
    7: ["Saturn in the 7th gives a mature, serious spouse, and marriage that tends to be delayed but is stable and committed.",
        "Business partnerships need patience; dealings with the public and employees are fair and disciplined.",
        "Coldness or distance in relationships is the cautionary side. This is also a Maraka house, so strain in close partnerships can affect health.",
        "Foreign trade or service can bring slow, steady gains."],
    8: ["Saturn is the natural karaka of the 8th: longevity is protected, and there is an interest in research, the occult and long-term investigations.",
        "Chronic illness, delays, obstacles and losses are the cautionary side; sudden events are met with endurance.",
        "Insurance, inheritance or pensions may come after a wait; the spouse's family may carry burdens.",
        "Surgery or accidents need care; regular routines protect health."],
    9: ["Saturn in the 9th gives a serious, disciplined approach to dharma; fortune comes late but is earned through hard work.",
        "Relations with the father or gurus may be distant or demanding; higher studies are slow and thorough.",
        "Pilgrimage and long-distance travel are undertaken with responsibility.",
        "Rigid beliefs are the cautionary side; thighs and hips need care."],
    10: ["Saturn in the 10th is a strong placement: career is built steadily through discipline and responsibility, and status grows with time.",
         "Administrative roles, service, labour-oriented professions, mining, iron, oil and management suit the placement.",
         "Recognition comes late but lasts; overwork and a hard-driving manner are the cautionary side.",
         "Knees and joints need regular care."],
    11: ["Saturn in the 11th gives steady, long-term gains; income grows slowly and desires are fulfilled through patient effort.",
         "Friends are older, serious and reliable; elder siblings may carry responsibilities.",
         "Large organisations, service sectors and the masses are favoured.",
         "Delays in gains and a small circle are the cautionary side."],
    12: ["Saturn in the 12th gives a disciplined approach to expenses, solitude and spiritual practice; foreign residence or isolation is possible.",
         "Sleep may be disturbed or limited; hospitals, jails, ashrams and charitable service are associated.",
         "Detachment brings growth; losses, delays and secret worries are the cautionary side.",
         "Feet, the left eye and joints need care."],
}

DATA["Rahu"] = {
    1: ["Rahu in the 1st amplifies the self: an unconventional, magnetic and driven personality with an obsessive streak.",
        "The person can look or behave differently from the family; identity may shift and illusion about the self is possible.",
        "Health and vitality can fluctuate in unusual ways; the body takes on whatever the person is obsessed with.",
        "Foreign matters often touch the life path."],
    2: ["Rahu in the 2nd amplifies the wish for wealth, family status and fine speech; sudden gains are possible, and so are sudden losses.",
        "Speech can be persuasive but exaggerated; food habits may be unusual or from other cultures.",
        "Family and lineage may be unconventional; foreign sources of income are possible.",
        "This is also a Maraka house; keep an eye on illusion in money matters."],
    3: ["Rahu in the 3rd amplifies courage, ambition and the drive to communicate; bold ventures in media, technology and marketing are favoured.",
        "Self-effort is intense and unconventional; short journeys and contacts abroad are frequent.",
        "The bond with younger siblings can be unusual; obsession with hobbies is possible.",
        "Over-confidence and exaggeration are the cautionary side."],
    4: ["Rahu in the 4th amplifies the wish for home, property and vehicles; residence away from the birthplace or abroad is possible.",
        "Peace of mind can be disturbed by restlessness and illusion; the mother or home life may be unconventional.",
        "Unusual or foreign education and sudden changes in home are indicated.",
        "Learning emotional contentment, rather than chasing the next home or vehicle, is the lesson."],
    5: ["Rahu in the 5th gives an unconventional, inventive intellect, with obsession in love, creativity, speculation and entertainment.",
        "Children or romance may come in unusual ways; delays or illusions about them are possible.",
        "Sudden gains in speculation are possible, but so are losses; mantra upasana steadies the mind.",
        "Higher education abroad or in modern fields is favoured."],
    6: ["Rahu in the 6th is strong: it helps win over enemies, debts and competition through unconventional methods.",
        "Service in foreign, technical or healing fields is favoured; the competitive spirit is intense.",
        "Unusual or hard-to-diagnose ailments and hidden enemies are the cautionary side.",
        "Rahu's drive in the 6th grows with experience, so results build gradually."],
    7: ["Rahu in the 7th amplifies desire in partnerships: the spouse or partner may be unconventional, foreign, or from a different background.",
        "Business partnerships and dealings with the public and foreign markets can bring sudden gains.",
        "Illusion and obsession in relationships are the cautionary side. This is also a Maraka house, so strain in close ties deserves attention.",
        "Clear boundaries and honest expectations keep partnerships healthy."],
    8: ["Rahu in the 8th gives a strong pull towards the occult, research, mysteries and hidden knowledge; sudden gains through inheritance or insurance are possible.",
        "Sudden, unexpected events and unusual circumstances are indicated; fear and illusion about death are the cautionary side.",
        "Mysterious, hard-to-diagnose ailments and obsessive fears about the body need regular care.",
        "Deep transformation, often through crisis, is the lesson of this placement."],
    9: ["Rahu in the 9th gives an unconventional view of dharma, foreign teachers and unusual paths of belief.",
        "Fortune can come through foreign matters; long-distance travel is likely.",
        "Relations with the father or gurus may be unusual or distant.",
        "Doubt and illusion about faith are the cautionary side."],
    10: ["Rahu in the 10th amplifies ambition and the drive for status; careers in technology, foreign trade, politics or unconventional fields suit the person.",
         "Sudden rises in career and public image are possible, but so are sudden setbacks.",
         "Reputation may involve a foreign link or an unusual path.",
         "Over-ambition and shortcuts to status are the cautionary side."],
    11: ["Rahu in the 11th is strong: it gives sudden gains, a large unconventional network and fulfilment of ambitions.",
         "Friends may be foreign or from different backgrounds; income comes in sudden or unusual ways.",
         "Large organisations, technology and the masses are favoured.",
         "Illusion about gains and overreach in desires are the cautionary side."],
    12: ["Rahu in the 12th amplifies foreign matters: residence abroad, travel and expenses on foreign soil are common.",
         "Sleep, dreams and illusion are intensified; hospitals, jails and secret enemies are associated.",
         "Spiritual practice and a regular sleep routine ground the restless mind.",
         "Hidden losses and unexpected expenses are the cautionary side."],
}

DATA["Ketu"] = {
    1: ["Ketu in the 1st gives a detached, introspective and spiritual personality, with an interest in mysticism.",
        "The person can seem aloof or distant; sudden changes in identity or outlook are possible.",
        "Past-life karma is strongly felt in the life path; the body may have unusual or hard-to-diagnose health issues.",
        "Finding a clear purpose and staying grounded in the body is the lesson."],
    2: ["Ketu in the 2nd gives detachment from wealth, family and fine speech; speech can be blunt, brief or silent.",
        "Sudden severance from family ties or savings is possible; spiritual values replace material ones.",
        "Food habits may be simple or ascetic.",
        "This is also a Maraka house; detachment from family can cause loneliness."],
    3: ["Ketu in the 3rd gives a detached courage and a mystical, intuitive way of communicating.",
        "Younger siblings may be distant, and self-effort comes in sudden bursts; research and spiritual writing suit the person.",
        "Short journeys may be to spiritual places.",
        "Lack of drive and disinterest in ordinary business are the cautionary side."],
    4: ["Ketu in the 4th gives detachment from the home, mother and property; peace of mind comes through spiritual practice.",
        "Sudden separation from home, the motherland or education is possible; the home may feel restless or unsettled.",
        "Property and vehicles are of little attachment.",
        "Emotional rootlessness is the lesson: inner peace has to be built rather than borrowed from the house."],
    5: ["Ketu in the 5th gives a mystical, intuitive intellect and strong poorva punya (past-life merit), with an interest in mantra and upasana.",
        "Children, romance and speculation may be delayed or detached; love can be spiritual rather than worldly.",
        "Higher studies in mystic or research fields are favoured.",
        "Detachment from creativity and losses in speculation are the cautionary side."],
    6: ["Ketu in the 6th is strong: it helps defeat enemies, debts and obstacles through detachment and intuition.",
        "Healing, research and service professions suit the person; disputes end suddenly.",
        "Unusual or hard-to-diagnose ailments are the cautionary side.",
        "Ketu's intuition in the 6th matures with age, and results improve with time."],
    7: ["Ketu in the 7th gives detachment in partnerships: the spouse or partner may be spiritual, distant or unconventional.",
        "Business partnerships may end suddenly; dealings with the public are reserved.",
        "Sudden separation or distance in marriage is the cautionary side. This is also a Maraka house, so close ties call for patience.",
        "Spiritual growth is the lesson in relationships."],
    8: ["Ketu in the 8th gives a strong interest in moksha, mysticism, research and the occult; past-life karma is felt through sudden transformations.",
        "Intuition is high; sudden events and unusual circumstances are indicated.",
        "Chronic or hard-to-diagnose ailments need care.",
        "Fear and attachment to the physical body are the cautionary side."],
    9: ["Ketu in the 9th gives a deep, mystic and detached approach to dharma, with spiritual teachers and past-life wisdom.",
        "Fortune comes through spiritual paths; relationships with the father or gurus may be distant or detached.",
        "Pilgrimage, meditation and time with a true teacher bring growth.",
        "Rejection of conventional belief and lack of direction are the cautionary side."],
    10: ["Ketu in the 10th gives detachment from status and career; success can come through research, spirituality, healing or behind-the-scenes work.",
         "Sudden changes or severance in career are possible.",
         "Public image is modest or enigmatic.",
         "Lack of ambition or direction is the cautionary side."],
    11: ["Ketu in the 11th is strong: it gives detachment from gains, friends and desires; a small, spiritual circle of friends is favoured.",
         "Gains come in sudden, unexpected ways; elder siblings may be distant.",
         "Ordinary desires and ambitions fade with spiritual practice, which can look like disinterest in gains.",
         "Sudden severance from friends and lack of ambition are the cautionary side."],
    12: ["Ketu in the 12th is a natural karaka placement: it favours moksha, meditation, isolation and spiritual practice.",
         "Foreign residence, hospitals, ashrams and retreats are associated; sleep and dreams are intuitive.",
         "Losses are accepted with detachment; sudden expenses are possible.",
         "Escapism, withdrawal and neglect of practical duties are the cautionary side."],
}


def _source(planet, house):
    if planet in PROFILE_FIELDS:
        left = f"PLANET_PROFILE[{planet}: {PROFILE_FIELDS[planet]}]"
    else:
        left = f"KARAKATWAS[{planet}: qualities, signifies]"
    return f"{left} + BHAVA_INFO[{house}: {HOUSE_FIELDS}]"


def rows():
    """The 96 curated rows as {planet, house, points, extra, status, source} in Moon … Ketu, house order."""
    return [{"planet": p, "house": h, "points": DATA[p][h], "extra": [], "status": "curated",
             "source": _source(p, h)}
            for p in ("Moon", "Mars", "Mercury", "Jupiter", "Venus", "Saturn", "Rahu", "Ketu")
            for h in range(1, 13)]
