"""Session 23 rule data as Python literals — the seed for Session23_Rules.xlsx.

Everything here is quoted or closely paraphrased from the Session 23 slides (page numbers in
`slide`/`source`) and the class recording.  After the first build the workbook is the editable
source of truth; this module is only used by `build_session23.py --seed`.
"""
from session23_sun_slides import SUN_SLIDE_TEXT

PLANETS = ["Sun", "Moon", "Mars", "Mercury", "Jupiter", "Venus", "Saturn", "Rahu", "Ketu"]

CLASSES = [
    dict(no=1, name="Kendra", slide_name="Kendra or Angular houses", houses=[1, 4, 7, 10],
         other_names="Vishnu Sthanas; Pillars of the Horoscope",
         nature="Very powerful, energetic and decisive houses; they give power for achievement and a strong will in life. 1st = person / self, 4th = happiness and comforts, 7th = interaction with the society and spouse, 10th = profession. Lagna is both a Kendra and a Trikona, hence extra strong and important. The distance between adjacent Kendras is always 90 degrees.",
         rule="Benefic grahas in Kendras lead to powerful manifestations with smaller efforts, while malefic grahas can cause struggle and pose challenges for accomplishments. Grahas placed here are highly active. Benefic planets in a Kendra enhance the internal strength of an individual.",
         slides="3-5"),
    dict(no=2, name="Trikona", slide_name="Trikona or Trines houses", houses=[1, 5, 9],
         other_names="Lakshmi Sthanas; Dharmasthanas",
         nature="The most auspicious houses (and their lords) in the chart. They bring spirituality, knowledge, goodness, generosity and well-being if well placed and unafflicted. 1st = self (Kendra and Trikona), 5th = intelligence and purva punya (Panapara), 9th = religion, fortune, inherited characters (Apoklima) — Kendra, Panapara and Apoklima indicate the balance. Adjacent Trikonas are 120 degrees apart; Trikona houses belong to the same tatwa, the same direction and the same varna.",
         rule="The planets posited in the Trikonas get closely associated with destiny and hence gain strength. Benefics here ease the flow of destiny; malefics could cause challenges to be faced.",
         slides="6-9"),
    dict(no=3, name="Panapara", slide_name="Panapara or Succedent houses", houses=[2, 5, 8, 11],
         other_names="Succedent; money related / wealth related",
         nature="Important for calculating one's financial status; they indicate the resources of the native. 2nd = one's own money, 5th = money earned by speculation, 8th = unexpected money, 11th = gain from profession or business. Panapara = accumulated or promised in future.",
         rule="Grahas posited in these places are moderately strong.", slides="10-11"),
    dict(no=4, name="Apoklima", slide_name="Apoklima or Cadent houses", houses=[3, 6, 9, 12],
         other_names="Cadent",
         nature="Apoklima houses indicate 'weakness', 'becoming less', 'expenditure' or 'destruction'. We spend money for ourselves and the body (12th), for family and relatives (3rd), for partner and to fulfil our desires (6th), and for parents and to maintain profession and status (9th) — each decreases the wealth.",
         rule="Planets placed in these signs are considered weak. Except 9th house, it is considered as bad position to the planets. Grahas in these houses are weak, very delicate, sensitive, highly intelligent, fluctuating, undecided and provide spiritual inclination to the native.",
         slides="12-13"),
    dict(no=5, name="Upachaya", slide_name="Upachaya or Increasing houses", houses=[3, 6, 10, 11],
         other_names="Houses of growth and prosperity; bending / self-effort houses",
         nature="Upachaya means improvement, growth or progress. They create a certain amount of urge / tension which drives one to improve life's situations and get better over time. 3rd = neck, 6th = waist, 10th = knees, 11th = ankle — body parts that can bend. The strength of Kendra and Trikona decides name, fame and monetary position; the strength of Upachaya shows potential and opportunities for personal growth / gains and refers to courage, duties, profession and gains.",
         rule="Planets placed in these houses grow and improve over time. Particularly, malefic planets placed in these houses bestow good results during their dasa period. Benefics in Kendra and malefics in Upachaya houses will provide good results.",
         slides="14-15"),
    dict(no=6, name="Apachaya", slide_name="Apachaya or Decreasing houses", houses=[1, 2, 4, 7, 8],
         other_names="Decreasing houses",
         nature="Houses 1, 2, 4, 7, 8 are Apachaya (decreasing) houses.",
         rule="Planets located in them lose their strength through time. Natural malefics do not do well in these houses.",
         slides="16"),
    dict(no=7, name="Maraka", slide_name="Maraka or Death-Inflicting (2nd and 7th) houses", houses=[2, 7],
         other_names="Marakasthanas; their lords are the Marakadipathis",
         nature="The 2nd and the 7th houses from the lagna are the marakasthanas (the death-inflicting houses), and the lords of the 2nd and the 7th are designated as the principal Marakas (the inflictors of death).",
         rule="Planets occupying or owning these houses can cause death during their dasa periods. If they operate before the time of death is promised, they can bring death like suffering, disturbance of the health etc.",
         slides="17-18"),
    dict(no=8, name="Dusthana", slide_name="Duhsthana or Evil houses", houses=[6, 8, 12],
         other_names="Trika houses; malefic houses",
         nature="The 6th, 8th and 12th houses are called evil houses. They are said to be evil and malefic houses; houses 6, 8 and 12 are extremely malefic (on the recording the 8th is the most malefic of the three).",
         rule="Lords of these houses bring problems, impediments, enemies, lawsuits, accidents, injuries, surgeries and death like experiences into our lives during their dasa-bukti period.",
         slides="19-20"),
    dict(no=9, name="Badhaka", slide_name="Badhaka or Obstruction houses", houses=None,
         other_names="Badhakasthana; its lord is the Badhakadipathi",
         nature="Badhaka means that which obstructs. Each sign has a particular sign corresponding to it which obstructs it. If Lagna falls in Chara Rashi, the 11th house is Badhakasthana and the 11th lord is Badhakadipathi; in Sthira Rashi, the 9th house and the 9th lord; in Dwiswabhava Rashi, the 7th house and the 7th lord.",
         rule="The Badhaka obstructs; it brings about barriers and disabilities or ends. But remember, badhaka obstructs a sign, it does not obstruct the horoscope. (Recording: its effects come in the dasa / bhukti of the Badhaka lord or of planets posted there — health issues, suffering; Yogakaraka and Badhaka are different concepts.)",
         slides="21-22"),
    dict(no=10, name="Trishadaya", slide_name="Trishadaya or Evil houses", houses=[3, 6, 11],
         other_names="Evil houses",
         nature="The 3rd, 6th and 11th houses represent the three evil factors — desire, anger and greed respectively. They are entirely opposite to the most important houses for spiritual advancement: the 9th, 12th and 5th houses respectively. The 11th house is the most powerful of the group as it is the last member.",
         rule="A person can achieve materialistic success and make lots of money only during the Maha Dasha period of the trishadaya houses. If the lord of a trishadaya house is a natural malefic like Saturn, Mars or Sun, and the malefic planet is also placed in its own house, the results given are simply amazing during its Maha Dasha.",
         slides="23-24"),
]

CLASS_RULES = [
    dict(**{"class": "Kendra"}, applies="benefic", exclude_houses=[], slide="4",
         text="Benefic grahas in Kendras lead to powerful manifestations with smaller efforts; they enhance the internal strength of the individual."),
    dict(**{"class": "Kendra"}, applies="malefic", exclude_houses=[], slide="4",
         text="Malefic grahas in Kendras can cause struggle and pose challenges for accomplishments."),
    dict(**{"class": "Kendra"}, applies="any", exclude_houses=[], slide="4",
         text="Grahas placed in a Kendra are highly active."),
    dict(**{"class": "Trikona"}, applies="benefic", exclude_houses=[], slide="7",
         text="Benefics in a Trikona ease the flow of destiny."),
    dict(**{"class": "Trikona"}, applies="malefic", exclude_houses=[], slide="7",
         text="Malefics in a Trikona could cause challenges to be faced."),
    dict(**{"class": "Trikona"}, applies="any", exclude_houses=[], slide="7",
         text="Planets posited in a Trikona get closely associated with destiny and gain strength."),
    dict(**{"class": "Panapara"}, applies="any", exclude_houses=[], slide="10",
         text="Grahas posited in the Panapara houses are moderately strong; these are money-related houses."),
    dict(**{"class": "Apoklima"}, applies="any", exclude_houses=[9], slide="12",
         text="Planets placed in the Apoklima houses are considered weak — delicate, sensitive, highly intelligent, fluctuating, undecided, with a spiritual inclination."),
    dict(**{"class": "Apoklima"}, applies="any", exclude_houses=[3, 6, 12], slide="12",
         text="The 9th house is the exception among the Apoklima houses: it is not counted as a bad position for the planets."),
    dict(**{"class": "Upachaya"}, applies="any", exclude_houses=[], slide="14",
         text="Planets placed in the Upachaya houses grow and improve over time."),
    dict(**{"class": "Upachaya"}, applies="malefic", exclude_houses=[], slide="14",
         text="A malefic planet placed here bestows good results during its dasa period."),
    dict(**{"class": "Apachaya"}, applies="any", exclude_houses=[], slide="16",
         text="Planets located in the Apachaya houses lose their strength through time."),
    dict(**{"class": "Apachaya"}, applies="malefic", exclude_houses=[], slide="16",
         text="Natural malefics do not do well in these houses."),
    dict(**{"class": "Maraka"}, applies="any", exclude_houses=[], slide="17",
         text="A planet occupying the 2nd or 7th can cause death-like suffering or disturbance of the health during its dasa, if it operates before the time of death is promised."),
    dict(**{"class": "Dusthana"}, applies="any", exclude_houses=[], slide="19",
         text="The 6th, 8th and 12th are evil and malefic houses; their lords bring problems, impediments, enemies, lawsuits, accidents, injuries and surgeries during their dasa-bukti period."),
    dict(**{"class": "Badhaka"}, applies="any", exclude_houses=[], slide="21",
         text="A planet in the Badhakasthana obstructs that sign and can bring barriers and disabilities."),
    dict(**{"class": "Trishadaya"}, applies="any", exclude_houses=[], slide="23",
         text="The 3rd, 6th and 11th stand for desire, anger and greed; they are opposite to the 9th, 12th and 5th."),
    dict(**{"class": "Trishadaya"}, applies="malefic", exclude_houses=[], slide="23",
         text="Natural malefics (Saturn, Mars, Sun) in the Trishadaya houses give very good material results during their Maha Dasha."),
]

BADHAKA_BY_MODE = {"Chara": 11, "Sthira": 9, "Dwisabhava": 7}   # the page spells the mode "Dwisabhava"

DIGNITY_EFFECT = {
    "Deep Exalted": dict(band="strong", status="taught", slide="31",
                         text="Exalted at the deep-exaltation degree: the karakatwas of the graha are bestowed in full force."),
    "Exalted": dict(band="strong", status="taught", slide="31",
                    text="Exalted: the karakatwas of the graha are bestowed in full force on this bhava's karakatwas."),
    "Own (Moolatrikona)": dict(band="strong", status="taught", slide="31",
                               text="In its Moolatrikona sign: exaltation / own house / MT sign quantify the results — the graha gives its karakatwas well."),
    "Own House": dict(band="strong", status="taught", slide="31",
                      text="In its own house: exaltation / own house / MT sign quantify the results — the graha gives its karakatwas well."),
    "Friend's House": dict(band="medium", status="blend", slide="12",
                           text="In a friend's house: the graha is supported and gives its karakatwas with ease."),
    "Neutral House": dict(band="medium", status="blend", slide="12",
                          text="In a neutral house: the results of the graha are moderate."),
    "Enemy's House": dict(band="weak", status="blend", slide="12",
                          text="In an enemy's house: the graha gives its karakatwas with difficulty."),
    "Debilitated": dict(band="weak", status="taught", slide="31",
                        text="Debilitated: the karakatwas come through diminished — when the Sun is strong there is confidence, when weak there is ego."),
    "Deep Debilitated": dict(band="weak", status="taught", slide="31",
                             text="Deep debilitation (near the exact degree) is the strongest form of debilitation: the karakatwas are heavily diminished, though the graha still gives results."),
}

DIGBALA = {   # house of directional strength; `lost` = the opposite house
    "Sun": dict(strong=10, lost=4, status="taught", source="Slides 33 and 39: Sun loses directional strength in the 4th and gains it in the 10th"),
    "Saturn": dict(strong=7, lost=1, status="standard", source="Recording: Saturn is powerful in the 7th (example given); the opposite house is the standard rule"),
    "Moon": dict(strong=4, lost=10, status="standard", source="Standard digbala table"),
    "Venus": dict(strong=4, lost=10, status="standard", source="Standard digbala table"),
    "Mercury": dict(strong=1, lost=7, status="standard", source="Standard digbala table"),
    "Jupiter": dict(strong=1, lost=7, status="standard", source="Standard digbala table"),
    "Mars": dict(strong=10, lost=4, status="standard", source="Standard digbala table"),
}

DASHA_ROLE_TEXT = {
    "Maraka lord": dict(kind="caution", slide="17",
        text="Lord of the 2nd or 7th — a principal Maraka. In its dasa / bhukti it can bring death-like suffering or disturbance of the health, if it operates before the time of death is promised."),
    "Maraka occupant": dict(kind="caution", slide="17",
        text="Occupies a Maraka house (2nd or 7th). Planets occupying these houses can bring suffering or disturbance of the health during their dasa periods."),
    "Badhakadhipati": dict(kind="caution", slide="21",
        text="Lord of the Badhaka house. In its dasa / bhukti it can obstruct — barriers, health issues and suffering may show up."),
    "Badhaka occupant": dict(kind="caution", slide="21",
        text="Occupies the Badhakasthana. In its period the obstruction of that sign can be felt."),
    "Dusthana lord": dict(kind="caution", slide="19",
        text="Lord of the 6th, 8th or 12th. In its dasa-bukti it can bring problems, impediments, enemies, lawsuits, accidents, injuries and surgeries."),
    "Trishadaya lord": dict(kind="favourable", slide="23",
        text="Lord of the 3rd, 6th or 11th. Material success and money come in the Maha Dasha of such a lord; if it is a natural malefic (Saturn, Mars, Sun) in its own house, the results are simply amazing."),
}

# What the teacher added on the recording for the Sun in each bhava (slides carry the main text).
SUN_EXTRA = {
    1: ["Looks authoritative with a bright face (tejas); the first house is also the face.",
        "Independent, self-made; does not like to take orders or work under anyone — a king cannot take orders.",
        "Egoistic, gives a lot of importance to the body and takes good care of themselves.",
        "Tendency to baldness or sparse hair (hot, pitta constitution; the Lagna is the head).",
        "Does not mingle easily: sits at a distance in gatherings and likes people to come to them (a Mercury Lagna person would go and talk to everybody).",
        "Royal bearing — walks upright and confident, often crosses the legs when sitting; very punctual; wants to be treated in a royal way; good name, fame and reputation."],
    2: ["Very proud of the family, lineage, family wealth and history, and likes to show it to the world.",
        "Father becomes the most important person in the family; high expectation from the family and a separative influence — may stay away from the family because of ego issues.",
        "Speech is commanding, authoritative and truthful, but the ego shows in it (boasting about self or family).",
        "Income may come from the family, father, government or father-in-law; a source of permanent income; the family may have a very good, royal reputation.",
        "Likes hot food, wheat-based food and spicy food.",
        "Strong Sun (e.g. exalted for Meena Lagna) gives confidence and leadership in full force; weak Sun (e.g. debilitated for Kanya Lagna) gives ego and lack of confidence."],
    3: ["Courageous and adventurous; bold, powerful communication; takes up responsibility and handles situations well; a limited number of co-borns.",
        "Writing is bold — presses hard while writing; the letter \"I\" is written big or bold (a strong sense of self); written communication is authoritative and to the point.",
        "Loves to initiate new projects; the efforts are visible to the outside world because the Sun cannot hide anything.",
        "Neighbours may be influential or in government; the younger co-born may be influential, in a government job or famous; support from influential people or government; travel for government work.",
        "May dominate the younger co-born, or be dominated by them."],
    4: ["Confident and proud of the home, the native place and the mother; the mother may be authoritative, dominating, egoistic, punctual, from a royal or influential family, or a good administrator.",
        "May live in a government-provided house, have stone cladding in front of the house or big windows with a lot of light; may use a government vehicle.",
        "Education in political science, administrative services or medicine, especially the heart.",
        "The 4th is the heart: an enlightened soul, good-hearted and balanced.",
        "Wherever the Sun is, activity of that bhava gives atma-tripti (soul satisfaction)."],
    5: ["Natural celebrities — they want the status of a celebrity or to be treated like one; creative pursuits are a source of ego satisfaction and confidence.",
        "The eldest child brings good name and fame; good relationship with children but high expectations and a separative influence (the Sun is a malefic planet).",
        "Purva punya is delivered through children; very good creativity; can become a good politician; higher education.",
        "Atma-tripti through creative activity and hobbies."],
    6: ["Can choose a career in the legal or medical field and shine there.",
        "Diseases: eye, heart, bone or heat-related problems.",
        "Debt (runa): can easily get loans from government organisations and banks.",
        "Very powerful, influential enemies; creates enemies through ego; may get diseases through bad eating habits or lifestyle, so health matters.",
        "Maternal uncle may be influential, proud or in government service.",
        "Atma-tripti through selfless service."],
    7: ["Ego issues in marriage and business partnerships — they should learn to be more humble; separations are possible.",
        "The spouse is well recognised, independent, egoistic, dominating, authoritative, with good administrative capacity; the business partner may be influential too.",
        "High expectation from the spouse or partner and a separative influence; the partner may try to dominate or control."],
    8: ["Confidence takes a beating through ups and downs and the ego is hurt, but they come out more confident through the hardships.",
        "Good researchers and astrologers; good for occult subjects, pranic healing and alternative medicine.",
        "One of the Moksha trikonas (4, 8, 12): the soul seeks enlightenment; they may become aware of the time of death and plan accordingly.",
        "Should not fall into bad habits such as drinking or smoking.",
        "Good fault finders — suited to quality control, since the bright Sun makes any fault visible.",
        "Inheritance from the father."],
    9: ["The father is dharmic and religious and gives importance to rituals and traditions; may be a good administrator; luck comes through the father (Bhagyasthana).",
        "Good teachers, professors and lawyers, focused on their life path.",
        "Confidence comes from knowledge and they love to share it — academic, religious, spiritual and philosophical; interest in a guru, and they get very good gurus."],
    10: ["Digbala: a very powerful position — good name, fame and recognition; wonderful for politicians and people in the public eye.",
         "Go into high positions such as CEO; administrative, authoritative, disciplined; their work is appreciated; they achieve their dreams through the profession.",
         "A burning desire to rise to the top; they will rise with hard work, but must keep the ego in check and give weight to co-workers' views.",
         "May be in a government job or a profession connected to the government; the mother-in-law may be dominating, egoistic and a good leader."],
    11: ["Focused on the fulfilment of desires; happy spending time with friends, who come from royal or influential families.",
         "An active social life, recognised in society, with good name and fame; the elder sibling shares these qualities, but being a separative planet the Sun can mean a strained relationship or living apart from the elder sibling.",
         "Atma-tripti through friendships and networking."],
    12: ["Lacks confidence and does not know their own worth; they gain confidence and authority in foreign lands, so should move away from the birthplace if given the chance.",
         "A Moksha trikona: the atma looks for moksha, so they are spiritual; spiritual activity gives atma-tripti.",
         "The bright Sun illuminates the 12th, so hidden enemies become visible.",
         "The relationship with the father may not be great, or they live far from the father; expenses may go towards the father or health."],
}

SUN_ROWS = []
for _h in range(1, 13):
    _slide, _text = SUN_SLIDE_TEXT[_h]
    SUN_ROWS.append(dict(planet="Sun", house=_h, points=[p.strip() for p in _text.split("\n\n") if p.strip()],
                         extra=SUN_EXTRA[_h], status="taught",
                         source=f"Slide {_slide} (verbatim) + class recording"))

TAUGHT_PAIRS = [
    dict(a="Mercury", b="Jupiter", status="taught", source="Slide 26 example + recording (Session 23)",
         conjunction="Jupiter is the jiva karaka — the individual; Mercury is intelligence, education, communication, oration and business. Together the individual is very intelligent, or likes business, or is very good in communication.",
         aspect=""),
]
